package el.ka.speechart.other

enum class Work {
  CREATE_ACCOUNT,
  CHECK_FIELDS,
  SIGN_UP,
  LOAD_USER,
  ADD_ADMIN,
  LOAD_USERS,
  LOAD_REQUESTS,
  DELETE_USER,
  DISAGREE_REQUEST,
  AGREE_REQUEST,
  LOAD_REVIEWS,
}